# syntax=docker/dockerfile:1

# Use an official Python runtime as the base image
FROM python:3.11.5

# Set the working directory in the container
WORKDIR /app
RUN pip3 install numpy==1.24.3
RUN pip3 install pandas==2.0.3
RUN pip3 install streamlit==1.43.2
RUN pip3 install pydeck==0.9.1
# Copy the local code to the container
COPY . /app


# Set the default command to run when the container starts
# CMD ["bash"]
CMD ["streamlit", "run", "app.py"]
